title: Dominic Motuka
description: My Personal Blog
author: Dominic Motuka
logo: /blog/assets/img/avatar.png
github: https://github.com/daumie
about: Freelance Web developer


baseurl: "https://daumie.github.io/blog"
url: "https://daumie.github.io/blog"

allowsearch: true


disqus_shortname: daumie
google_analytics: UA-80222908-1

      
social:

    - icon: fa-github
      link: 'https://github.com/daumie'
    - icon: fa-stack-exchange
      link: 'http://stackexchange.com/users/5999356/daumie'
    - icon: fa-linkedin
      link: 'https://ke.linkedin.com/in/dominic-motuka'
    - icon: fa-twitter
      link: 'https://twitter.com/MotukaD'
    - icon: fa-facebook
      link: 'https://www.facebook.com/dominic.motuka'
      icon: fa-google
      link: 'mailto:dominic.motuka@gmail.com'
    
    
    

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: ""
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]